### ISSUE TITLE
usage of input name `exclude` are same as SamKirkland?

### ISSUE THREAD

**Issue by ShortArrow** [MajorVengeance/Ftp-Deploy-Action#3]
# Overview

Isn't it easier to understand how to use `exclude`?

# Purpose

This ext is convenient, so I want more users to use it.

# Proposal content

- Added to Reademe
- If usage of input name `exclude` are same as [ReadMe](https://github.com/SamKirkland/FTP-Deploy-Action#readme) of SamKirkland/FTP-Deploy-Action, Is it easy to understand if about it is written?

# Task

- [ ] Example of use for a single file
- [ ] Example of use for multiple files
- [ ] Glob usage example
- [ ] Example of use for directories

# Error I got when I tried

```
      --name: LFTP Deploy
        uses: MajorVengeance / Ftp-Deploy-Action@v0.2.3-alpha
        with:
          ftp_host: $ {{secrets.FTP_SERVER}}
          ftp_username: $ {{secrets.FTP_USERNAME}}
          ftp_password: $ {{secrets.FTP_PASSWORD}}
          local_source_dir: ./build/
          dist_target_dir: $ {{secrets.FTP_REMOTE_DIR_DEVELOP}}
          delete: true
          exclude:
            --blog
            --.env
            --.well-known
          disable_ssl_certificate_verification: true

 Check failure on line 55 in .github / workflows / deploys.yml

GitHub Actions
/ Build and Deploy
Invalid workflow file
The workflow is not valid. .github / workflows / deploys.yml (Line: 55, Col: 13): A sequence was not expected
```

**Comment by ShortArrow** [comment]
@MajorVengeance  When I was thinking, I had more questions.
Is this a destination exclusion setting or a source exclusion setting?
